### ISSUE TITLE
Notification Favourite/Un-favorite doesn't work. Nor the notification icon changes accordingly.

### ISSUE THREAD

**Issue by Vishcot** [fast4x/RiMusic#1145]
### Steps to reproduce the bug

1. Play any song
2. Close app goto notification panel
3. Un-favorite or favorite song.

### Expected behavior

1. It should have changed favourite to un-favorite and vice-versa in app as well but sometimes it does nothing.
2. Should change its color (from getting filled to unfilled icon and vice-versa) 

### Actual behavior

1. Whether you favorite a song or un-favorite icon same icon will be shown (it sometimes makes it hard to understand it is favourited or un-favorited)
And also many times it doesn't even work from notification buttons.

https://github.com/fast4x/RiMusic/assets/136909951/a0b571b3-cdea-4971-ad9d-072c3f82822c

### RiMusic version

0.6.26.1

### Android version

Android 14

**Comment by fast4x** [comment]
i think it's fixed in version 0.6.27

**Comment by Vishcot** [comment]
@fast4x uhmm, its still not fixed dev 🥺

**Comment by fast4x** [comment]
I understand, still persist? uhm ok in my devices it's ok

**Comment by Vishcot** [comment]
> I understand, still persist? uhm ok in my devices it's ok

Yeah, for me it is still persisting! 
Idk how to extract a bug report, otherwise i would have shared it with you.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.28
