### ISSUE TITLE
Multiple monthly playlist for the same month

### ISSUE THREAD

**Issue by cMattw** [fast4x/RiMusic#1758]
### Steps to reproduce the bug

1. Go to library 
2. See the monthly playlist

### Expected behavior

It should only show one playlist for the month

### Actual behavior

It shows multiple same playlist for the month

### Screenshots/Screen recordings

![Screenshot_2024-05-04-11-45-42-553_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/160244930/b8911d8e-2295-4942-9c2b-e1f58fcfa854)

### RiMusic version

0.6.33

### Android version

Android 13

**Comment by dAtA-TRoN** [comment]
My list is getting longer and longer as well 🫨😂.

**Comment by fast4x** [comment]
ok I'll check it

**Comment by fast4x** [comment]
I think now is fixed, available from version 0.6.34

**Comment by fast4x** [comment]
I've activated delete option so can delete duplicate if occur

**Comment by fast4x** [comment]
https://github.com/fast4x/RiMusic/tree/master/customVersion
Download custom version, delete action is enabled in monthly playlists and is possible disable creation of monthly playlists from ui settings

**Comment by dAtA-TRoN** [comment]
> Download custom version, delete action is enabled in monthly playlists and is possible disable creation of monthly playlists from ui settings

Perfect, I was able to delete all 5 duplicates. Thank you, Sir 🤠!

**Comment by dAtA-TRoN** [comment]
I just want letting you know that duplication still happens 🫠...

![Screenshot_2024-05-07-19-30-12-16_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/fast4x/RiMusic/assets/71184627/62c0a898-f964-4fb4-a395-048c7815e23d)

**Comment by fast4x** [comment]
yes, disable for now

**Comment by NikunjKhangwal** [comment]
My duplicate playlists are still there after update, how to fix?

**Comment by fast4x** [comment]
disable for now

**Comment by NikunjKhangwal** [comment]
Ok 👌🏼
