### ISSUE TITLE
Playlist, Back button

### ISSUE THREAD

**Issue by AfafAsyraf** [fast4x/RiMusic#246]
### Steps to reproduce the bug

When creating a blank playlist it cannot be deleted. Community playlist that shown a lot of songs only showing 10/15 songs. Back button when wanna close the app is not working.

### Expected behavior

Playlist can be deleted and showing community playlist songs all of it. Back button function 

### Actual behavior

Can't be deleted the playlist and songs shown not all of them. 

### Screenshots/Screen recordings

![Screenshot_20231218-080713](https://github.com/fast4x/RiMusic/assets/154100704/5ae8f0fd-c95a-4893-a3bf-e74d55f1a341)
![Screenshot_20231218-080757](https://github.com/fast4x/RiMusic/assets/154100704/a9092859-b7f0-4eef-87cf-da3c60cbc672)
![Screenshot_20231218-080803](https://github.com/fast4x/RiMusic/assets/154100704/6d3b1a7c-848b-45e5-a206-72956fe72fe8)

### RiMusic version

0.6.13

### Android version

Android 13

**Comment by fast4x** [comment]
Ok, bug confirmed.
Thanks

**Comment by fast4x** [comment]
Fixed menu on empty playlist.
available from 0.6.14

**Comment by DeadSecTr** [comment]
Is there any option to sort the playlist from Newest/oldest on top/bottom? 

Btw...thanks for the great app!
It works for me great!

Cheers

**Comment by fast4x** [comment]
Not, but you can request this feature ☺️

**Comment by AfafAsyraf** [comment]
Issues still occured. Playlist and back button still cannot go back. I have
updated to the version that you have fixed.

**Comment by fast4x** [comment]
Yes I know, this ticket is not closed in fact.

**Comment by AfafAsyraf** [comment]
Ahh okayy 👍🏼

**Comment by AfafAsyraf** [comment]
It prompted saying there's a bug it keeps crashing and not loading music
lists.

**Comment by AfafAsyraf** [comment]
After cache clean it fixed

**Comment by fast4x** [comment]
Relative Back button function
Added option in setting for enable/disable Close app with back button.
Available from 0.6.15

**Comment by fast4x** [comment]
> After cache clean it fixed

it fixed after? correct?

**Comment by AfafAsyraf** [comment]
Still occuring after opening app. Keeps crashing and prompting app got bugs
