### ISSUE TITLE
Swipe changing song doesn't work; theme mode is changing itself

### ISSUE THREAD

**Issue by Zokii0** [fast4x/RiMusic#2557]
### Steps to reproduce the bug
1st issue:
1. Play some music
2. Swipe left or right doesn't work properly

2nd issue: 
1. Using dark mode
3. Go to settings
4. Change something in settings related to player
5. Theme changes to pitch black

3rd issue:
1. Using dark mode
2. Play some music
3. Rotate phone to landscape view
4. Theme changes to pitch black
6. Rotate phone to portrait/regular view
7. Theme stays on pitch black

### Expected behavior

Swipe for changing song should work.

Theme of app shouldn't change when changing any other settings and when rotating phone.

### Actual behavior

Swipe for changing song doesn't work.

Theme changes.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/144468403/40247045-638e-48d3-a014-5c141f4901e0

https://github.com/fast4x/RiMusic/assets/144468403/861ae2a7-b512-4b49-831c-31b44bc72620

### RiMusic version

0.6.41

### Android version

Android 14

### Additional information

Found similar issue http://github.com/fast4x/RiMusic/issues/2339

**Comment by privacyfreak84** [comment]
The theme issue will never be fixed, it seems. I've been trying for months to get it fixed, but it seems that any issue mentioning this gets no attention from anyone 😢

**Comment by Zokii0** [comment]
I just saw update of app and really hopped they'll fix all/any of my mentioned issues, but they did none of it. Only thing i noticed that swipe song works ONLY if you move fingers very fast and short, and abnormally tiering your hand/fingers with such a fast movement in order to swipe song. Not sure if that was the case before this last update, but overall nothing above is fixed 😔

**Comment by privacyfreak84** [comment]
😢

**Comment by privacyfreak84** [comment]
> but it seems that any issue mentioning this gets no attention from anyone

Every single other issue by me has been resolved, even ones reported after the theme one. But not this one...

**Comment by Zokii0** [comment]
Another update, still nothing fixed. When i needed the most, i couldn't swipe song in bus while using 1 hand. When it comes to themes, only customized one won't change, but i wish to have "material you" theme, and i can't get/copy that same color from "material you" in "customized".
@fast4x can you please take a look at these? Maybe you missed this post?

**Comment by Zokii0** [comment]
Oh okay, i'm sorry for being little rude, i respect and appreciate your hard work on app, especially for seing updates very frequently with lots of new things in such a short time. I really love this app, i just thought that my post was skipped as irrelevant, or unnoticed, but glad you looked at it and that you assured me that you do fixing it and read everything, take as much time as you need!

**Comment by fast4x** [comment]
use player modern

**Comment by Zokii0** [comment]
This is much better now, thanks! Only thing left is if it could swipe horizontally instead of vertically, maybe to make option in settings to chose one of those two, but it's not a deal breaker, it is still way better than before, so i'll close this issue.

**Comment by fast4x** [comment]
Vertical swiping = carousel..

**Comment by Zokii0** [comment]
Disabling carousel (in my case) doesn't disable vertical swipping, neither enables horizontal swipping. I tried going through all different settings in terms of changing interface and all options where i have to choose between modern and essential, but nothing makes horizontal swipe works, so guess disabling carousel doesn't do much. But like i said, i'm still glad i can easily swipe songs.
