### ISSUE TITLE
[Feature]: Highlighted text background

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#2581]
### Description

The lyrics can be harder to read on certain backgrounds.

### Suggested Solution

If possible try implementing this kind of highlighted background where not just the current text become bold (which it already does in RiMusic) but also a white or black highlight line appear behind text to make it pop out.

![IMG_20240701_213202](https://github.com/fast4x/RiMusic/assets/99175083/7092086e-67b6-49c7-8111-8dfd98e1f1a4)

**Comment by aneesh1122** [comment]
try these:
1) activate Lyrics outline -> theme
or
2) Lyrics Color -> accent

This might improve visibility.

If you were using white Lyrics I would have suggested to enable glow

**Comment by NikunjKhangwal** [comment]
It does improve visibility but it doesn't look good.

**Comment by fast4x** [comment]
@aneesh1122 try

**Comment by aneesh1122** [comment]
> @aneesh1122 try

I tried. It's not possible.

**Comment by aneesh1122** [comment]
![WsaClient_O3Od090Djk](https://github.com/fast4x/RiMusic/assets/45353488/eb99af45-bafd-45d0-b6f6-0c4df080a20a)

**Comment by fast4x** [comment]
Try to enlarge to fit with screen width...

**Comment by aneesh1122** [comment]
> Try to enlarge to fit with screen width...

Couldn't do it. The lyrics are inside a scrollable 

> Try to enlarge to fit with screen width...

That's the most I could do. My first try was to fill the whole width.

**Comment by aneesh1122** [comment]
I think this is good enough. It gets the job done at least. Maybe in the future me, you or someone else can get back to this and make it fill the whole width.

**Comment by NikunjKhangwal** [comment]
Can corners be rounded like this?
![IMG_20240702_091156](https://github.com/fast4x/RiMusic/assets/99175083/c04e7873-692b-45f1-97f0-c3be53695be4)

This is still indeed good enough

**Comment by aneesh1122** [comment]
> Can corners be rounded like this?
> ![IMG_20240702_091156](https://github.com/fast4x/RiMusic/assets/99175083/c04e7873-692b-45f1-97f0-c3be53695be4)
> 
> This is still indeed good enough

No

**Comment by NikunjKhangwal** [comment]
Fair enough, it's still good

**Comment by fast4x** [comment]
> > Can corners be rounded like this?
> > ![IMG_20240702_091156](https://github.com/fast4x/RiMusic/assets/99175083/c04e7873-692b-45f1-97f0-c3be53695be4)
> > 
> > This is still indeed good enough
> 
> No

Why not? it's nice...

**Comment by aneesh1122** [comment]
> Can corners be rounded like this?
> ![IMG_20240702_091156](https://github.com/fast4x/RiMusic/assets/99175083/c04e7873-692b-45f1-97f0-c3be53695be4)
> 
> This is still indeed good enough

![Screenshot_2024-07-02-12-43-37-784_it.fast4x.rimusic.debug.jpg](https://github.com/fast4x/RiMusic/assets/45353488/adac5ed7-be54-4b81-a3f6-51fe027c2620)

I hope this is going to be the last thing because I ain't doing anything more with this. I got other Important things to fix or add. @fast4x it's time we move on from this issue.

Also, when someone does something for you the least you can do is be grateful even if it's "good enough"

**Comment by fast4x** [comment]
I am grateful to you and thank you for the implementations you have made. You can’t just rely on what you think, you have to take into account other users who ask for some improvements. This is the spirit of RiMusic, I myself have done and continue to develop things that someone asked including you.

You used the term "most important things" in reality everything is important, at most there are important things with more priorities than others.

Again, thanks for your time.

**Comment by aneesh1122** [comment]
> I am grateful to you and thank you for the implementations you have made. You can’t just rely on what you think, you have to take into account other users who ask for some improvements. This is the spirit of RiMusic, I myself have done and continue to develop things that someone asked including you.
> 
> You used the term "most important things" in reality everything is important, at most there are important things with more priorities than others.
> 
> Again, thanks for your time.

I have immense respect for you and for what you do. In fact you are the one who Inspired me to learn kotlin and do things. I wasn't talking about you. I'll always be grateful to you and I never miss a chance to thank you whenever you develop things I asked. I even thank you when you implement someone else's request.

The grateful part was for @NikunjKhangwal.

I know everything should be considered Important but tell me one major streaming service which gives highlight option. I added different colors and outlines options still it wasn't enough for him. He could have just increased the font size if he had problems with reading words. He can fix his own problems but he wants us to fix his problems.

even when we fix his problems he uses words like "good enough" and come up with something new. Never once did he thank anyone here even after I changed things 3 times for him.

**Comment by NikunjKhangwal** [comment]
@aneesh1122 Hey man, listen

1. First of all every issue i open here is by default for @fast4x as he's the main developer here. Including this one. I didn't asked you to implement it from the get go, it was after fast asked you to implement it so i went with it. Infact I never mentioned you in any new issue i made so these requests aren't for you.
2. No matter who's working on it, i try not to force something. Even yesterday i opened a issue about low quality notification thumbnail but fast said it's not possible so i just said ok and closed it. You can check all of my previous issues for record, a lot of them ended up right away because they were headache to implement for dev. If you're talking about asking for something in the first place then it is a open source project and i have to right to suggest or request something. Same way you have the right to deny something. That's the nature of FOSS. Again i want to mention these requests are for fast.
3. You said "it's good enough" first that's why i was just agreeing to it. This isn't something i made up myself here. I don't know why this is a problem?
> I think this is good enough. It gets the job done at least. Maybe in the future me, you or someone else can get back to this and make it fill the whole width.
4. "Never once did he thank anyone" is a stretch. Well here's the [comment](https://github.com/fast4x/RiMusic/issues/2535#issuecomment-2199134154) from just yesterday where i thanked you. By saying "anyone" you're speaking on the behalf of others too, mainly fast which isn't correct. I've thanked him many times as well, feel free to ask him.
[Tho i'm genuinely surprised you forgot about the words you used a few hours ago and yesterday conversation so quickly]
5. I didn't asked you to implement different colors or outlines, that's something you did for yourself and others. I know a lot of hard work went into it but i'm free to not use a feature i don't want. You can enjoy it. By saying "still it wasn't enough for him" you're making it sound like i ordered you to do it, this isn't the right response. Font size is different thing, highlight is different. I can choose to find a perfect balance for my needs. Changing font size isn't a "fix", solution and workaround are two different things. "he wants us to fix his problems." By saying "us" you're once again speaking on behalf of fast who never had problem fixing my problems. It's boring to repeat things but i just want to say one last time you never have to fix or implement something i asked for, fast will do it if he agrees. Thanks and have a nice day.

**Comment by aneesh1122** [comment]
> @aneesh1122 Hey man, listen
> 
> 1. First of all every issue i open here is by default for @fast4x as he's the main developer here. Including this one. I didn't asked you to implement it from the get go, it was after fast asked you to implement it so i went with it. Infact I never mentioned you in any new issue i made so these requests aren't for you.
> 2. No matter who's working on it, i try not to force something. Even yesterday i opened a issue about low quality notification thumbnail but fast said it's not possible so i just said ok and closed it. You can check all of my previous issues for record, a lot of them ended up right away because they were headache to implement for dev. If you're talking about asking for something in the first place then it is a open source project and i have to right to suggest or request something. Same way you have the right to deny something. That's the nature of FOSS. Again i want to mention these requests are for fast.
> 3. You said "it's good enough" first that's why i was just agreeing to it. This isn't something i made up myself here. I don't know why this is a problem?
> 
> > I think this is good enough. It gets the job done at least. Maybe in the future me, you or someone else can get back to this and make it fill the whole width.
> 
> 4. "Never once did he thank anyone" is a stretch. Well here's the [comment](https://github.com/fast4x/RiMusic/issues/2535#issuecomment-2199134154) from just yesterday where i thanked you. By saying "anyone" you're speaking on the behalf of others too, mainly fast which isn't correct. I've thanked him many times as well, feel free to ask him.
>    [Tho i'm genuinely surprised you forgot about the words you used a few hours ago and yesterday conversation so quickly]
> 5. I didn't asked you to implement different colors or outlines, that's something you did for yourself and others. I know a lot of hard work went into it but i'm free to not use a feature i don't want. You can enjoy it. By saying "still it wasn't enough for him" you're making it sound like i ordered you to do it, this isn't the right response. Font size is different thing, highlight is different. I can choose to find a perfect balance for my needs. Changing font size isn't a "fix", solution and workaround are two different things. "he wants us to fix his problems." By saying "us" you're once again speaking on behalf of fast who never had problem fixing my problems. It's boring to repeat things but i just want to say one last time you never have to fix or implement something i asked for, fast will do it if he agrees. Thanks and have a nice day.

I'm not going to reply to every point of yours. All I'm saying is when someone helps you out you should be grateful.
There's a difference between "Can corners be rounded like this?" and "Hey man, thanks for implementing this. do you think you could make corners rounded like this?". You're getting my point. right? even if it's not what you exactly wanted you should be grateful for what you got and then you can of course request to improve it.

I was about to ignore this request of yours. @fast4x asked me to try it so I implemented it. I respect him so I couldn't ignore him.

I could have easily rounded the corners. It wasn't a big deal. The reason why I replied with "No" is because you came off as ungrateful.

Have a nice day

**Comment by fast4x** [comment]
Please be calm, these are just misunderstandings that can be solved in peace. Each has its own character.

**Comment by NikunjKhangwal** [comment]
> I'm not going to reply to every point of yours.

This is exactly what we call ignorance. I tried to prove my points logically based on past incidents and even you know it.

> All I'm saying is when someone helps you out you should be grateful. 

Except when i did yesterday you forgot about it and even had the audacity to go out and say "he never thanked once" now. How are you going to defend this factually?

> There's a difference between "Can corners be rounded like this?" and "Hey man, thanks for implementing this. do you think you could make corners rounded like this?". You're getting my point. right? even if it's not what you exactly wanted you should be grateful for what you got and then you can of course request to improve it.

Except when i say "it's still good", it's a compliment. These are basic english expressions, i shouldn't be explaining something like this. I'll admit maybe i could've included a additional Thanks as well but what's the point when you proved later you can't remember 'em?

> I was about to ignore this request of yours. @fast4x asked me to try it so I implemented it. I respect him so I couldn't ignore him.

That's exactly what i'm saying. You did it on fast's request not me.

You ignore expression and compliments when they're given, flame me for things i didn't asked for yet expect a good response in return. Isn't this ironical?

**Comment by aneesh1122** [comment]
> This is exactly what we call ignorance. I tried to prove my points logically based on past incidents and even you know it

Naah, I just don't want to waste my time

> Except when i did yesterday you forgot about it and even had the audacity to go out and say "he never thanked once" now. How are you going to defend this factually?

He did it once and is now going to bring it up always. How many 'thanks' and 'please' from you do you see here in this issue? You ran out of 'thanks'?  

> I'll admit maybe i could've included a additional Thanks as well but what's the point when you proved later you can't remember 'em?

You admit and still trying to act superior by mentioning **one time** you thanked me yesterday. even in that issue thread you acted as if I'm working on your payroll until you _thanked_ me

> That's exactly what i'm saying. You did it on fast's request not me.

doesn't mean you can't be grateful when someone does something for you, directly or indirectly.

**Comment by NikunjKhangwal** [comment]
> Naah, I just don't want to waste my time

Most common excuse ever. Plus you wouldn't make a fuss about such small things if you didn't had the time. At least stick to one thought.

> He did it once and is now going to bring it up always. How many 'thanks' and 'please' from you do you see here in this issue? You ran out of 'thanks'?

Yes i will if get blamed for it.

> You admit and still trying to act superior by mentioning one time you thanked me yesterday. even in that issue thread you acted as if I'm working on your payroll until you thanked me

At least i'm sane enough to admit my weaknesses. You still can't explain why you said "never" so you're just trying to repeat yourself here. Another common thing. Common ground doesn't mean superiority.

> doesn't mean you can't be grateful when someone does something for you, directly or indirectly.

> Let me tell you something **Basic**. when someone uses their time to do something for you to help you out, you thank that person along with compliments. That's basic etiquette. If someone does something for you and even if it's not successful, you thank that person for even attempting it.

Once again "good" is a compliment so that's at least something and i already admitted my part. I didn't completely tried to ignore your words/work like you did to me.

> btw didn't you say you want to end this? why did you reply me then?

No i didn't. When i said one last time i referred to the last point specific to comment. Also you're replying as well, so much for "superiority" when doing the same thing. Once again proving your excuse. If you didn't had the time you would just ignore the thread alltogether but you're sparing the time real nice now.

**Comment by NikunjKhangwal** [comment]
Also mention your platform of choice and we can talk this there, not in issue that was supposed to be about app.

**Comment by fast4x** [comment]
Now stop! Please.

**Comment by NikunjKhangwal** [comment]
> Now stop! Please.

Sorry fast this isn't the kind of argument i can ignore. I can however do this somewhere else and not here as mentioned previously.

**Comment by aneesh1122** [comment]
> at least something and i already admitted my part

Good. That's all I wanted you to do from the beginning. If it wasn't for your arrogance and entitlement we could have avoided all this nonsense.

Now, since you've admitted it, start acting on it and be grateful to anyone who helps you in the future.

**Comment by NikunjKhangwal** [comment]
@aneesh1122 Mention a platform of choice or hope on Telegram. I don't want to continue here.

**Comment by aneesh1122** [comment]
> @aneesh1122 Mention a platform of choice or hop on Telegram. I don't want to continue here.

And you think I want to continue ANYWHERE? I keep ungrateful and arrogant people like you away from me as much as possible. Why would I want to have anything to do with you.

Let's end it here. Enjoy using the text highlight option and expanded lyrics **I Implemented**. Deep down you'll always thank me whenever you use them. 😂😂

**Comment by NikunjKhangwal** [comment]
> And you think I want to continue ANYWHERE? I keep ungrateful people like you away from me as much as possible. Why would I want to have anything to do with you.

Yet you keep replying because you want to prove a point. How much of a hypocrite can you be? Excuses over excuses without body.

> Let's end it here. Enjoy using the text highlight option and expanded lyrics **I Implemented.** Deep down you'll always thank me whenever you use them. 😂😂

Superiority complex ah! Thanks for proving my point earlier.

**Comment by fast4x** [comment]
I said enough, if you have to argue do it outside of my project.
