### ISSUE TITLE
Problem with skipping songs when the screen is off

### ISSUE THREAD

**Issue by bellatrix-8** [fast4x/RiMusic#3044]
### Steps to reproduce the bug

Version 0.6.45.1: Playlist is played correctly from beginning to end in the car via Bluetooth. However, when you go to the previous or next song, the time counts down but the song does not play. When you unlock the phone, the song starts playing. The same problem occurs on the lock screen.
Version 0.6.44 was working. I am sorry for my English.

### Expected behavior

.

### Actual behavior

.

### RiMusic version

0.6.45.1

### Android version

12

**Comment by bellatrix-8** [comment]
https://github.com/user-attachments/assets/68a1d811-220a-4223-b090-11cc8c236c05

**Comment by aneesh1122** [comment]
install the new custom version. Maybe that will fix your problem cuz I'm not having this problem.

**Comment by bellatrix-8** [comment]
Custom edition is the same

**Comment by bellatrix-8** [comment]
0.6.44 version https://github.com/user-attachments/assets/a86ab9ad-2007-426a-b0c3-7418c8347730

**Comment by bellatrix-8** [comment]
https://github.com/user-attachments/assets/d7ba008c-82ec-428a-99fd-76ebab7893b7

0.6.44 version

**Comment by aneesh1122** [comment]
> https://github.com/user-attachments/assets/d7ba008c-82ec-428a-99fd-76ebab7893b7
> 
> 0.6.44 version
> I reverted to version 0.6.44.

Most of the problems are solved after doing a clean install. If you've reverted to 0.6.44 you've already lost your cached songs.

Maybe give it an another try and clean install latest custom version.

**Comment by bellatrix-8** [comment]
Thank you. I tried to install the latest custom version and official version with clean installation. But I have the same problem with version 0.6.45.1. I will continue with version 0.6.44 for now.

**Comment by InioX** [comment]
Also happens to me but even when the screen is on. Skipping songs in the status bar has the same issue, to fix it you just have to open the app again.

**Comment by bellatrix-8** [comment]
> Also happens to me but even when the screen is on. Skipping songs in the status bar has the same issue, to fix it you just have to open the app again.

Thank you very much for your help. Reopening the app does not solve the problem. Actually, this problem did not exist after the first update. Even though I did not change any settings, the problem appeared after a few hours and it still continues even after a clean installation. It is annoying to deal with this problem in the car or on a bluetooth speaker. This problem does not exist in version 0.6.44. I will continue with this old version and another app until this problem is solved with a new update.

**Comment by bellatrix-8** [comment]
https://github.com/user-attachments/assets/28bd6b52-a1ad-4228-8557-8b06846002e0

This problem has been solved with version 0.6.46. Thank you very much.

**Comment by aneesh1122** [comment]
> https://github.com/user-attachments/assets/28bd6b52-a1ad-4228-8557-8b06846002e0
> 
> This problem has been solved with version 0.6.46. Thank you very much.

Glad to know that :)

Enjoy
