### ISSUE TITLE
ADD SONG TO PIPED FROM RIMUSIC

### ISSUE THREAD

**Issue by PPereaC** [fast4x/RiMusic#3152]
### Steps to reproduce the bug

Hello. I am experiencing an issue with adding a song from rimusic to piped via the rimusic app. When I add a song and then synchronize the playlist, the song disappears and not added to the piped playlist. Can you please assist me with resolving this problem?. Thank you.

### Expected behavior

:)

### Actual behavior

:)

### RiMusic version

Last

### Android version

13

### Additional information

https://github.com/user-attachments/assets/0e597b1b-83af-490b-aaf7-96c2ad771e58

**Comment by fast4x** [comment]
Hi enable debug in miscellaneous settings, try to add song to piped, copy log and paste here

**Comment by PPereaC** [comment]
Sorry, but Piped is not working. The piped.video website also not working for me. I don't know if is a general problem. When I can log in I tell you and paste the log

**Comment by PPereaC** [comment]
I can't get the error log. When I try to do it with debug option no error shown so the log is empty :(

**Comment by coolswapnil** [comment]
Hope this log will help, I have followed the steps as mentioned and copied log as below.

2024-08-09 09:02:06:574 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-09 09:02:22:202 DEBUG: u - CheckMonthlyPlaylist false

2024-08-09 09:04:02:067 DEBUG: u - CheckMonthlyPlaylist false

**Comment by fast4x** [comment]
Strange there isn't any error

**Comment by coolswapnil** [comment]
I tried 2-3 times issue is there as mentioned but in log it is not captured.

**Comment by coolswapnil** [comment]
Hope this log will help.  Log is captured with latest version of app:0.6.47.1

2024-08-11 16:10:51:783 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-11 16:10:51:992 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:10:51:992 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:10:52:032 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:10:52:033 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:11:01:777 DEBUG: c - CheckMonthlyPlaylist false

**Comment by coolswapnil** [comment]
Log with version 0.6.48

2024-08-11 16:16:53:473 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:16:53:474 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:16:53:484 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:16:53:484 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:17:16:761 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:17:16:762 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:17:16:775 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:17:16:775 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:02:173 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:02:174 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:02:188 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:02:189 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:41:203 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:41:204 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:41:222 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:41:223 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:56:602 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:56:603 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:56:617 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:18:56:619 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:19:41:623 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:19:41:624 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:19:41:643 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:19:41:643 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:20:59:935 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:20:59:936 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:20:59:955 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:20:59:955 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:34:24:850 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:34:24:851 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 0, -1, B_6d3RBiEN0, 6]
2024-08-11 16:34:24:864 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:34:24:864 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 647, -1, B_6d3RBiEN0, 6]
2024-08-11 16:34:32:131 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET B_6d3RBiEN0, 3589240, -1, B_6d3RBiEN0, 6]
2024-08-11 16:34:32:131 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key B_6d3RBiEN0 all DataSpec[GET B_6d3RBiEN0, 3589240, -1, B_6d3RBiEN0, 6]
2024-08-11 16:34:32:131 INFO: q - PlayerService createDataSourceResolverFactory videoId B_6d3RBiEN0
2024-08-11 16:34:32:423 INFO: q - PlayerService createDataSourceResolverFactory bodyVideoId B_6d3RBiEN0 videoId B_6d3RBiEN0
2024-08-11 16:34:32:424 INFO: q - PlayerService createDataSourceResolverFactory audioQualityFormat AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=153524, averageBitrate=142592, contentLength=4010795, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=225021, lastModified=1707814830391356, loudnessDb=-1.5799999, audioSampleRate=48000, url=https://rr1---sn-gwpa-2o9l.googlevideo.com/videoplayback?expire=1723395872&ei=wJq4ZofnLPqs3LUPgOjIoQs&ip=2409%3A40c2%3A1056%3A3b4c%3A3056%3Ae5ff%3Afebf%3A4486&id=o-APCCWTVQWu2O8Bcuv8BvMSSex0I7PDlrSv5d0IL-kacN&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=W5&mm=31%2C29&mn=sn-gwpa-2o9l%2Csn-gwpa-cvhd&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=40&initcwndbps=372500&spc=Mv1m9i00d9KQhhs8R2Hl919iuRd0q3AO05Vh&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=4010795&dur=225.021&lmt=1707814830391356&mt=1723373828&fvip=1&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAPCQJGkZTap0lZFsDNlnA4LdAf4geUCWwsK3s7AR-CqgAiBPLGUEGGbJ1TBoEcGIOyqc04DiXS2tJlVDi1yyY4m_SA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgCy72sYP57RbVqXQXOz6h5DKiqt1zZApnxemq18NOrfcCIAd-6P3IBtCo-E6EBpVrFFd1B7QvM7WpdjWx0Hi6LEi_)
2024-08-11 16:34:33:863 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET tOM-nWPcR4U, 0, -1, tOM-nWPcR4U, 6]
2024-08-11 16:34:33:864 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key tOM-nWPcR4U all DataSpec[GET tOM-nWPcR4U, 0, -1, tOM-nWPcR4U, 6]
2024-08-11 16:34:33:865 INFO: q - PlayerService createDataSourceResolverFactory videoId tOM-nWPcR4U
2024-08-11 16:34:34:129 INFO: q - PlayerService createDataSourceResolverFactory bodyVideoId tOM-nWPcR4U videoId tOM-nWPcR4U
2024-08-11 16:34:34:130 INFO: q - PlayerService createDataSourceResolverFactory audioQualityFormat AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=142700, averageBitrate=131845, contentLength=2442454, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=148201, lastModified=1715024592685607, loudnessDb=-1.8699999, audioSampleRate=48000, url=https://rr4---sn-gwpa-2o9l.googlevideo.com/videoplayback?expire=1723395874&ei=wpq4ZufXG6GVz7sP37rdqQY&ip=2409%3A40c2%3A1056%3A3b4c%3A3056%3Ae5ff%3Afebf%3A4486&id=o-ABk4MIMKTLddf0TTAq6Cii-mSJbBi5wGpqUz134XjoQa&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=kA&mm=31%2C29&mn=sn-gwpa-2o9l%2Csn-gwpa-cvhe7&ms=au%2Crdu&mv=m&mvi=4&pl=40&initcwndbps=372500&spc=Mv1m9tXtJB0y0EUjLasjI5nTTWvipOprfiQ-&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=2442454&dur=148.201&lmt=1715024592685607&mt=1723373828&fvip=4&keepalive=yes&c=ANDROID_MUSIC&txp=4502434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhANvTTmzXCfUHvFBeNM-U2QPeCoN34j9NEsrsHK4ttrk7AiEA-aeZzBfgq3vkO8iusSloJ6ZHvj10lsoBT3nYFPjt1Ok%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgGjI_a26SSIPa2eHMu7q6rfmlm4k3d9FfasmLobUzEtwCIB6EAMiN17kbMAq9A0Rz1MSTPvo_ftxXUmXkpkwU0ayA)
2024-08-11 16:34:35:221 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET tOM-nWPcR4U, 524288, -1, tOM-nWPcR4U, 6]
2024-08-11 16:34:35:221 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false key tOM-nWPcR4U all DataSpec[GET tOM-nWPcR4U, 524288, -1, tOM-nWPcR4U, 6]
2024-08-17 20:49:55:053 DEBUG: MainApplication - Log enabled at /data/user/0/it.fast4x.rimusic/files/logs
2024-08-17 20:49:55:281 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET cAQtS4vIRQs, 0, -1, cAQtS4vIRQs, 6]
2024-08-17 20:49:55:282 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId cAQtS4vIRQs all DataSpec[GET cAQtS4vIRQs, 0, -1, cAQtS4vIRQs, 6]
2024-08-17 20:49:55:282 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInCache true
2024-08-17 20:49:55:282 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-08-17 20:49:55:282 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-08-17 20:49:55:282 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-08-17 20:49:55:336 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET cAQtS4vIRQs, 2940819, -1, cAQtS4vIRQs, 6]
2024-08-17 20:49:55:336 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId cAQtS4vIRQs all DataSpec[GET cAQtS4vIRQs, 2940819, -1, cAQtS4vIRQs, 6]
2024-08-17 20:49:55:336 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInCache false
2024-08-17 20:49:55:337 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-08-17 20:49:55:337 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-08-17 20:49:55:337 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-08-17 20:49:55:337 INFO: q - PlayerService createDataSourceResolverFactory videoId cAQtS4vIRQs
2024-08-17 20:49:55:919 INFO: q - PlayerService createDataSourceResolverFactory bodyVideoId cAQtS4vIRQs videoId cAQtS4vIRQs
2024-08-17 20:49:55:920 INFO: q - PlayerService createDataSourceResolverFactory adaptiveFormats available [AdaptiveFormat(itag=137, mimeType=video/mp4; codecs="avc1.640020", bitrate=137031, averageBitrate=71583, contentLength=1657877, audioQuality=null, approxDurationMs=185280, lastModified=1709333275360844, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=1657877&dur=185.280&lmt=1709333275360844&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAKBTh9c8iKX3mEihO-U7BsWKbLI_iDu7Lce2grAIdVOTAiEAlhbr5z6KOzLx-dM9WqRBVNHH8Vrq_KZBozy3ble6Vg4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=248, mimeType=video/webm; codecs="vp9", bitrate=477270, averageBitrate=231755, contentLength=5367461, audioQuality=null, approxDurationMs=185280, lastModified=1709333524789630, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=248&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=5367461&dur=185.280&lmt=1709333524789630&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgaQN2BKpoTugyB5iHY_CspjzlGZgdKX52tp9oVZs6K-cCIQD6gByW_8XXmXURf0I3OQjKqyu1XGyKQoyLOFatemf-8Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=136, mimeType=video/mp4; codecs="avc1.4d401f", bitrate=54590, averageBitrate=30616, contentLength=709067, audioQuality=null, approxDurationMs=185280, lastModified=1709333774368677, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=709067&dur=185.280&lmt=1709333774368677&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAKYOJZ4iuiGrwKggt_S_GXivGEti79cnVl5ZfabC2AYAAiBlhHlnn6maaARjMHBgHUGwKL0061VObD0l9QG0RLkO-g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=247, mimeType=video/webm; codecs="vp9", bitrate=278380, averageBitrate=136924, contentLength=3171164, audioQuality=null, approxDurationMs=185280, lastModified=1709334024515752, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=247&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=3171164&dur=185.280&lmt=1709334024515752&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAIG0qNRymSKGI7Mf_0XAkY3dkzTjOofqDTQleB9p8g2eAiEAkDMLbdCIpuj5FQjIqVpIvtZWXwbXBCbTAqguRpUEbxo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=135, mimeType=video/mp4; codecs="avc1.4d401e", bitrate=40065, averageBitrate=22505, contentLength=521237, audioQuality=null, approxDurationMs=185280, lastModified=1709333774382729, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=135&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=521237&dur=185.280&lmt=1709333774382729&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgHO2y2pIUDvnhfw7VkEBMGeXvY3j8tbzlFps-dvrn5D4CIEcviED_ikwPEZXLOGGiEZ8zDEWNYnhK5ZuX4xYQQ8_z&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=244, mimeType=video/webm; codecs="vp9", bitrate=157314, averageBitrate=77638, contentLength=1798098, audioQuality=null, approxDurationMs=185280, lastModified=1709333774367633, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=244&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=1798098&dur=185.280&lmt=1709333774367633&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgT9JR1b8Pj-L71uF5k_Ejy8jxqcrUbpDN_tjIWeV0Lh0CIQCeZGtPzmPJRDZA17tsuu8B1UJCTBKXt_KaguccjkkvhA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=134, mimeType=video/mp4; codecs="avc1.4d4015", bitrate=29297, averageBitrate=17128, contentLength=396687, audioQuality=null, approxDurationMs=185280, lastModified=1709334532447708, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=134&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=396687&dur=185.280&lmt=1709334532447708&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAOD_SMGiLIHVwxZv6adqk3PKGUrVrYM-5ohQUU3uvIjGAiBB_uweDt-wKwjvA5O8nS-gcB2QnarrwHIZYSoJSU8DAg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=243, mimeType=video/webm; codecs="vp9", bitrate=107451, averageBitrate=53798, contentLength=1245963, audioQuality=null, approxDurationMs=185280, lastModified=1709334024417612, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=243&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=1245963&dur=185.280&lmt=1709334024417612&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgG2bPEVWIuYe0ZAh5Bvm0rotS_sWTC33Q1mJePKfmJnACIQChBxSiHrS_XUyq3zRSg1Z_HzAdFzgc1J9hdRs2cskgVw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=133, mimeType=video/mp4; codecs="avc1.4d400c", bitrate=18307, averageBitrate=11573, contentLength=268040, audioQuality=null, approxDurationMs=185280, lastModified=1709333774333306, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=133&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=268040&dur=185.280&lmt=1709333774333306&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgd9wULgqyp0IAHEyQznoZ74umYLLUUSle9_nn7NM3KZkCIQCpWLO5nt6_IzNMR2f3lNZWphLXCJrUMyGMixqOnQxxyA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=242, mimeType=video/webm; codecs="vp9", bitrate=65009, averageBitrate=26175, contentLength=606228, audioQuality=null, approxDurationMs=185280, lastModified=1709334024480927, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=242&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=606228&dur=185.280&lmt=1709334024480927&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAI7zGg8wx8S1IWEb-TTJS7b5OBjWxzk7ZYk1JF96bvLYAiEA9j33C6QcgB_uQNy57YFGBaOrckBPrBLM-VWjIZdEkQI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=160, mimeType=video/mp4; codecs="avc1.4d400b", bitrate=10553, averageBitrate=7818, contentLength=181067, audioQuality=null, approxDurationMs=185280, lastModified=1709333774396261, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=160&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=181067&dur=185.280&lmt=1709333774396261&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALYGHGWrszcxmwnJsjBYBbWDVwD83I8nw_zsUs75eRgmAiBmQ0HNU9og2JiVllMhugcBR7puaXQFtg89qeBBD1Xo7w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=278, mimeType=video/webm; codecs="vp9", bitrate=33121, averageBitrate=18143, contentLength=420194, audioQuality=null, approxDurationMs=185280, lastModified=1709333774405418, loudnessDb=null, audioSampleRate=null, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=420194&dur=185.280&lmt=1709333774405418&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALQylM8f_bgh9Gv4_yInP8hNg8bmvQ2loaIXbDgE33pbAiA_Fx9V6qM2V5lqjIrbTVcnqGdZJwb6x7TQawDqSsJiCw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=139, mimeType=audio/mp4; codecs="mp4a.40.5", bitrate=50387, averageBitrate=48857, contentLength=1132025, audioQuality=AUDIO_QUALITY_LOW, approxDurationMs=185360, lastModified=1709332512002412, loudnessDb=-0.010000229, audioSampleRate=22050, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=139&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=1132025&dur=185.360&lmt=1709332512002412&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIvV-C9wc4vg2rLvc1EG_D_z7myNhoI8RP4UuaU92uGLAiBpLWeP0QJSQ-DruaOnNQ5AxbP3ZyedoETpfi4Bznd1QQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=140, mimeType=audio/mp4; codecs="mp4a.40.2", bitrate=131029, averageBitrate=129591, contentLength=3001575, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=185294, lastModified=1709332512035920, loudnessDb=-0.010000229, audioSampleRate=44100, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=3001575&dur=185.294&lmt=1709332512035920&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAPgpo9XRhQ2jG4W218otMXbED7kHLFYKW1_ay3XbME3JAiEA2HeZoBvaChbcogXS25jHJqZnzt2RlMS5E3OkjeLogPI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=249, mimeType=audio/webm; codecs="opus", bitrate=57732, averageBitrate=53169, contentLength=1231669, audioQuality=AUDIO_QUALITY_LOW, approxDurationMs=185321, lastModified=1714729927079876, loudnessDb=-0.010000229, audioSampleRate=48000, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=249&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=1231669&dur=185.321&lmt=1714729927079876&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgYfND_uyeFmQqyYj2vVeaMPqiBVEbjI8tLJ8TEYhd3hACIC4gzC1TjZgh__UvlmPU8YpgV3NHjwy9Bg7FY-7h8-EK&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=250, mimeType=audio/webm; codecs="opus", bitrate=77833, averageBitrate=70157, contentLength=1625213, audioQuality=AUDIO_QUALITY_LOW, approxDurationMs=185321, lastModified=1714729933058860, loudnessDb=-0.010000229, audioSampleRate=48000, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=250&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=1625213&dur=185.321&lmt=1714729933058860&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAKhB9N6XgfwOF4zssvf4-dWAkdkdC3WzGLFXmznNS3lLAiA7z1-b8seXW-Z2WY3raaQENeFWeMKOS13kJGVQx2teOg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D), AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=148391, averageBitrate=137845, contentLength=3193214, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=185321, lastModified=1714729966351090, loudnessDb=-0.010000229, audioSampleRate=48000, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=3193214&dur=185.321&lmt=1714729966351090&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgd9kSAvosHcTMqWZFgFCC4Psn1bYm8YTuEp4MOwcs9PgCIQCDPnsGdODh0EBf7gNRg9nceXu9g_JY3g3RlBrkLUu8JQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D)]
2024-08-17 20:49:55:920 INFO: q - PlayerService createDataSourceResolverFactory audioQualityFormat selected AdaptiveFormat(itag=251, mimeType=audio/webm; codecs="opus", bitrate=148391, averageBitrate=137845, contentLength=3193214, audioQuality=AUDIO_QUALITY_MEDIUM, approxDurationMs=185321, lastModified=1714729966351090, loudnessDb=-0.010000229, audioSampleRate=48000, url=https://rr3---sn-gwpa-o5bez.googlevideo.com/videoplayback?expire=1723929595&ei=m7_AZu2hKJeV1d8P8ZL5mAM&ip=2409%3A40c2%3A102b%3Adc57%3A4ae%3A2fff%3Afe4c%3A9d03&id=o-AMCEQ8fjxjLZvGtQRaE7MY07XpxTx9DN63tBjucwRYfa&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=-f&mm=31%2C29&mn=sn-gwpa-o5bez%2Csn-gwpa-pmhd&ms=au%2Crdu&mv=m&mvi=3&pl=40&gcr=in&initcwndbps=311250&spc=Mv1m9lJsq_pIIHXl8WORpriKVpkCUi96_fPS&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=3193214&dur=185.321&lmt=1714729966351090&mt=1723907606&fvip=2&keepalive=yes&c=ANDROID_MUSIC&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgd9kSAvosHcTMqWZFgFCC4Psn1bYm8YTuEp4MOwcs9PgCIQCDPnsGdODh0EBf7gNRg9nceXu9g_JY3g3RlBrkLUu8JQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAKJwmR_OEuB9jOGJmasVmFX9OeyMmF2DH5dWbq8yBjr2AiEAq6ApvDpp23RjzCtkbn-0_lSiOW5gzVeSQSNgPSo5-Hk%3D)
2024-08-17 20:49:55:939 INFO: q - PlayerService createDataSourceResolverFactory dataSpec DataSpec[GET mjbeVxitxiU, 0, -1, mjbeVxitxiU, 6]
2024-08-17 20:49:55:939 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isLocal false videoId mjbeVxitxiU all DataSpec[GET mjbeVxitxiU, 0, -1, mjbeVxitxiU, 6]
2024-08-17 20:49:55:939 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInCache true
2024-08-17 20:49:55:939 INFO: q - PlayerService createDataSourceResolverFactory dataSpec isInDownloadCache false
2024-08-17 20:49:55:939 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer0 false
2024-08-17 20:49:55:939 INFO: q - PlayerService createDataSourceResolverFactory dataSpec videoId == ringBuffer1 false
2024-08-17 20:50:07:986 DEBUG: a - CheckMonthlyPlaylist false
2024-08-17 20:50:08:862 DEBUG: b0 - SyncPipedUtils ImportPipedPlaylists playlists 2
2024-08-17 20:50:13:361 DEBUG: d - SyncPipedUtils checkPipedAccount Piped account connected
2024-08-17 20:50:13:955 DEBUG: k0 - SyncPipedUtils syncSongsInPipedPlaylist playlistId 22 songs 355

**Comment by fast4x** [comment]
Your playlist isn't a piped playlist, this is the cause that not sync. Try this, go to piped.video, create a new playlist, from RiMusic sync all playlist, now when add a song to this playlist it will be synced.

**Comment by PPereaC** [comment]
What a log!! 🤣. I hope this helps to solve it!

**Comment by PPereaC** [comment]
> Your playlist isn't a piped playlist, this is the cause that not sync. Try this, go to piped.video, create a new playlist, from RiMusic sync all playlist, now when add a song to this playlist it will be synced.

I tried with a piped playlist and the result is the same that my video on the top.

**Comment by coolswapnil** [comment]
> Your playlist isn't a piped playlist, this is the cause that not sync. Try this, go to piped.video, create a new playlist, from RiMusic sync all playlist, now when add a song to this playlist it will be synced.

I have used piped playlist only and I have created it in same as you mentioned.

**Comment by fast4x** [comment]
Ok I'll check it

**Comment by fast4x** [comment]
Fixed, available from version 0.6.49

**Comment by stefanhra** [comment]
So when will 0.6.49 be released and/or are there nightly builds somewhere I can try? 

Thanks.

**Comment by fast4x** [comment]
New release every Friday

**Comment by stefanhra** [comment]
Very good, thank you.

**Comment by stefanhra** [comment]
I am still experiencing this issue or something very similar on Rimusic v0.6.52. I create a new Piped playlist and add songs to it. When I open the new playlist the songs appear there for a moment then disappear. Should I open a new issue or am I doing something wrong.
