### ISSUE TITLE
list of songs by an artist or group

### ISSUE THREAD

**Issue by ifz5** [fast4x/RiMusic#3365]
### Steps to reproduce the bug

Go to artist
Go to songs
Play 

### Expected behavior

Should advance list of songs of the artist or group

### Actual behavior

After the tenth song it returns to the first one. It does not advance from song number 10 on the list.

### RiMusic version

0.6.48 by fast4x

### Android version

Android 13

**Comment by fast4x** [comment]
I've tried and it works with the same artist. Explain better want you do .

**Comment by ifz5** [comment]
Let me give you an example:
I choose the band Queen, once I choose their playlist of songs I press play. It starts with the first song in the playlist on the player. If I skip ahead to the next song, there comes a time when the playlist stops loading and the next song doesn't load or it returns me to the first song. All this happens when I've skipped ahead to song number 10 approximately.

**Comment by ifz5** [comment]
sorry, why is it closed?

**Comment by fast4x** [comment]
Because i think it's fixed in latest release, download and try please.

**Comment by ifz5** [comment]
Thank you for your support.
Best regards

**Comment by fast4x** [comment]
You are welcome, send me feedback please if it work.

**Comment by ifz5** [comment]
Sorry, I updated the app and it still doesn't work

**Comment by ifz5** [comment]
I have updated the app and it still won't load more than 5-10 songs in the playlist
