### ISSUE TITLE
Can't download in the new version

### ISSUE THREAD

**Issue by Jabwss** [fast4x/RiMusic#5026]
### Version of RiMusic

0.6.65

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Bro I don't even have to explain always happens in a new version

**Comment by Xyxhxx** [comment]
Similar problem for me.. I have zero playback no matter if the song is cached or not. Every song results in an error 🤦‍♂️

**Comment by Eli-dev2008** [comment]
A mí tampoco me funciona ¿Será un error de la actualización?

**Comment by oilheir** [comment]
Probably for the best, the new version fucked everything for us and we can't play any songs lmao

**Comment by fast4x** [comment]
Fixed available from version 0.6.65.1

**Comment by oilheir** [comment]
> Fixed available from version 0.6.65.1

Is v 0.6.65.1 gonna be available later today? Cuz so far the latest appears to be the 65 one... Also did you guys implement album title on the player for the 65.1 version?

**Comment by fast4x** [comment]
i think tonight

**Comment by 6XChen** [comment]
> Fixed available from version 0.6.65.1

Not yet? 😭😭

**Comment by Chulco** [comment]
> > Fixed available from version 0.6.65.1
> 
> Not yet? 😭😭

Still not working, 65.1 have the same issues, songs have playback errors
